name: retail-genai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - cudatoolkit=12.1
  - pytorch=2.1.2
  - torchvision=0.16.2
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyterlab=4.0.5
  - ipywidgets=8.0.7
  - scikit-learn=1.3.0
  - tqdm=4.65.0
  - pillow=10.0.0
  - pip:
    - transformers==4.30.2
    - accelerate==0.20.3
    - diffusers==0.18.2
    - sentence-transformers==2.2.2
    - opencv-python==4.7.0.72
    - albumentations==1.3.1
    - langchain==0.0.267
    - openai==0.27.8
    - tiktoken==0.4.0
    - gradio==3.33.1
    - streamlit==1.24.0
    - plotly==5.15.0
    - pyyaml==6.0
    - python-dotenv==1.0.0
    - fastapi==0.100.0
    - uvicorn==0.23.1
    - pymilvus==2.2.11
    - pyarrow==12.0.1
    - duckdb==0.8.1
    - requests==2.31.0
    - pytest==7.4.0
    - black==23.7.0
    - flake8==6.0.0
    - isort==5.12.0
    - pytest-cov==4.1.0
